# Generated by Django 5.0.6 on 2024-07-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personarol',
            name='representante',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Profesor', 'Profesor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.persona')),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='estudiantes.padre'),
        ),
    ]
