# Generated by Django 5.0.6 on 2024-07-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_personarol_representante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='perfil',
        ),
    ]
