# Generated by Django 5.0.6 on 2024-07-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_remove_persona_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
    ]
